name: magic_tower_origin
description: magic tower origin

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2


#  share_extend:
#    path: ./plugin/ShareExtend
  share_extend:
    git:
      url: git://github.com/genius158/ShareExtend.git


dev_dependencies:
  flutter_localizations:
    sdk: flutter

  flutter_test:
    sdk: flutter

  rxdart: ^0.19.0
  fluttertoast: ^2.2.1
  path_provider: ^0.4.1
  shared_preferences: ^0.4.3
  simple_permissions: ^0.1.9
  file_picker: ^1.1.1

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - lib/locale/i18n_en.json
    - lib/locale/i18n_zh.json

    - innermap/map.json

    - images/icon_load_diy.png
    - images/icon_diy_level.png
    - images/icon_inner_game.png
    - images/Item01-05_1_1.png

    - images/blade1.png
    - images/Item01-01_1_1.png
    - images/Item01-01_1_3.png
    - images/Item01-01_1_2.png
    - images/Actor01-Braver01_1_1.png
    - images/Item02-09_3_1.png
    - images/Item01-08_3_1.png
    - images/Item04-XXMT03_1_2.png
    - images/Item01-05_1_4.png
    - images/user_info_bg.jpg
    - images/Actor01-Braver01.png
    - images/Actor02-Monster06_1_1.png
    - images/Actor02-Monster01_1_1.png
    - images/Event01-Wall01.png
    - images/Item01-02.png
    - images/Event01-Door01.png
    - images/Item01-01.png
    - images/Monster01-01_2_1.png
    - images/Monster06-01.png
    - images/Monster03-01.png
    - images/Item01-Gem01.png
    - images/Item01-08.png
    - images/floor.png
    - images/Other09.png
    - images/Monster02-01_1_1.png
    - images/Actor02-Monster02_1_1.png
    - images/Monster02-01_2_1.png
    - images/Monster02-01_3_1.png
    - images/Monster02-01_4_1.png
    - images/Monster09-01_1_1.png
    - images/Monster09-01_2_1.png
    - images/Monster05-01_1_1.png
    - images/Monster05-01_2_1.png
    - images/Monster05-01_3_1.png
    - images/Monster07-04_1_1.png
    - images/Monster02-01_4_1.png
    - images/Monster07-01_1_1.png
    - images/Monster07-01_2_1.png
    - images/Monster04-01_1_1.png
    - images/Monster01-04_4_1.png
    - images/Monster11-01_1_1.png
    - images/Monster08-01_1_1.png
    - images/Monster07-08_1_1.png
    - images/Actor02-Monster14_1_1.png
    - images/Monster06-02_1_1.png
    - images/stone_monster.png
    - images/Item01-06_2_1.png
    - images/Item01-06_2_3.png
    - images/Item01-06_2_2.png
    - images/Actor02-Monster01.png
    - images/Actor02-Monster02.png
    - images/Actor02-Monster14.png
    - images/item_select.png



  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages